Update fetch-conjur-secret.yml

diff --git a/.github/workflows/fetch-conjur-secret.yml b/.github/workflows/fetch-conjur-secret.yml
--- a/.github/workflows/fetch-conjur-secret.yml
+++ b/.github/workflows/fetch-conjur-secret.yml
@@ -27,6 +27,13 @@ jobs:
         echo "Authenticating..."
         FULL_AUTHN_URL=$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate
         echo "Calling authn URL: $FULL_AUTHN_URL"
+        RESPONSE=$(curl -i -s -w "\n%{http_code}" \
+          --request POST \
+          --data "$CONJUR_API_KEY" \
+          "$FULL_AUTHN_URL")
+        echo "Full /authenticate response:"
+        echo "$RESPONSE"
+        BODY=$(echo "$RESPONSE" | sed '$d')
         STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
         if [ "$STATUS_CODE" != "200" ]; then
           echo "Authentication failed"
@@ -35,31 +42,25 @@ jobs:
           echo "$BODY"
           exit 1
         fi
-        echo "Authentication successful"
-        AUTHN_TOKEN=$(curl -s -k \
-        --header "Accept-Encoding: base64" \
-        --data "$CONJUR_API_KEY" \
-        "$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate") && \
-        if [ -z "$AUTHN_TOKEN" ]; then echo "❌ Failed to authenticate"; exit 1; fi && \
+        AUTHN_TOKEN=$(echo "$BODY" | base64 | tr -d '\r\n')
         echo "$AUTHN_TOKEN"
-        
+        echo "Authentication successful"
         echo "=============================="
         echo "Fetching secret..."
         RAW_PATH=data%2Fvault%2Fconjurtest%2Fmysecret%2Fpassword
         SECRET_URL=$CONJUR_APPLIANCE_URL/api/secrets/$CONJUR_ACCOUNT/variable/$RAW_PATH
         echo "Secret fetch URL: $SECRET_URL"
-        SECRET=$(curl -s -k \
-          -H "Authorization: Token token=\"$AUTHN_TOKEN\"" \
-          "$SECRET_URL") && \
-        # SECRET_VALUE=$(echo "$SECRET" | head -n1)
-        # SECRET_STATUS=$(echo "$SECRET" | tail -n1)
+        SECRET=$(curl -s -w "\n%{http_code}" \
+          -H "Authorization: Token token=$AUTHN_TOKEN" \
+          "$SECRET_URL")
+        SECRET_VALUE=$(echo "$SECRET" | head -n1)
+        SECRET_STATUS=$(echo "$SECRET" | tail -n1)
         echo "Secret fetch status: $SECRET_STATUS"
-        # if [ "$SECRET_STATUS" != "200" ]; then
-        #   echo "Failed to fetch secret"
-        #   echo "Response:"
-        #   echo "$SECRET"
-        #   exit 1
-        # fi
+        if [ "$SECRET_STATUS" != "200" ]; then
+          echo "Failed to fetch secret"
+          echo "Response:"
+          echo "$SECRET"
+          exit 1
+        fi
         echo "$SECRET_VALUE"
         echo "Retrieved secret: $SECRET_VALUE"
- 
