Update fetch-conjur-secret.yml

diff --git a/.github/workflows/fetch-conjur-secret.yml b/.github/workflows/fetch-conjur-secret.yml
--- a/.github/workflows/fetch-conjur-secret.yml
+++ b/.github/workflows/fetch-conjur-secret.yml
@@ -35,27 +35,31 @@ jobs:
         FULL_AUTHN_URL=$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate
         echo "Calling authn URL: $FULL_AUTHN_URL"
  
-        RESPONSE=$(curl -i -s -w "\n%{http_code}" \
-          --request POST \
-          --data "$CONJUR_API_KEY" \
-          "$FULL_AUTHN_URL")
+        # RESPONSE=$(curl -i -s -w "\n%{http_code}" \
+        #   --request POST \
+        #   --data "$CONJUR_API_KEY" \
+        #   "$FULL_AUTHN_URL")
+         AUTHN_TOKEN=$(curl -s -k --request POST \
+         --data "$CONJUR_API_KEY" \
+         "$CONJUR_APPLIANCE_URL/api/authn/$CONJUR_ACCOUNT/$CONJUR_AUTHN_LOGIN/authenticate" \
+         | base64 | tr -d '\r\n')
  
         echo "Full /authenticate response:"
-        echo "$RESPONSE"
- 
-        BODY=$(echo "$RESPONSE" | sed '$d')
-        STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
- 
-        if [ "$STATUS_CODE" != "200" ]; then
-          echo "Authentication failed"
-          echo "Status: $STATUS_CODE"
-          echo "Body:"
-          echo "$BODY"
-          exit 1
-        fi
- 
-        AUTHN_TOKEN=$(echo "$BODY" | base64 | tr -d '\r\n')
         echo "$AUTHN_TOKEN"
+ 
+        # BODY=$(echo "$RESPONSE" | sed '$d')
+        # STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
+ 
+        # if [ "$STATUS_CODE" != "200" ]; then
+        #   echo "Authentication failed"
+        #   echo "Status: $STATUS_CODE"
+        #   echo "Body:"
+        #   echo "$BODY"
+        #   exit 1
+        # fi
+ 
+        # AUTHN_TOKEN=$(echo "$BODY" | base64 | tr -d '\r\n')
+        # echo "$AUTHN_TOKEN"
         #::add-mask::
         echo "Authentication successful"
         echo "=============================="
