Update fetch-conjur-secret.yml

diff --git a/.github/workflows/fetch-conjur-secret.yml b/.github/workflows/fetch-conjur-secret.yml
--- a/.github/workflows/fetch-conjur-secret.yml
+++ b/.github/workflows/fetch-conjur-secret.yml
@@ -83,11 +83,11 @@ jobs:
         SECRET_STATUS=$(echo "$SECRET" | tail -n1)
  
         echo "Secret fetch status: $SECRET_STATUS"
-        if [ "$SECRET_STATUS" != "200" ]; then
-          echo "Failed to fetch secret"
-          echo "Response:"
-          echo "$SECRET"
-          exit 1
-        fi
+        # if [ "$SECRET_STATUS" != "200" ]; then
+        #   echo "Failed to fetch secret"
+        #   echo "Response:"
+        #   echo "$SECRET"
+        #   exit 1
+        # fi
         
         echo "Retrieved secret: $SECRET_VALUE"
